feat: implement parallel schedule generation and refactoring
jakji93/airon-fitness pull request #52
Opened 2023-07-15 19:45 UTC by d-x-s

A private route that requires authentication.
Access with `userprofile/generate`. 

Sample:
![image](https://github.com/d-x-s/airon-fitness/assets/68035358/d89ea470-4906-4bcf-96ef-9c9ffaa2e654)

Actual Output: 
`
{
    "userInfoID": "649fb93b7d3e204da2a565a7",
    "workoutSchedule": "{\n  \"schedule\": {\n    \"Monday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Chest press\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 150\n        },\n        {\n          \"exercise\": \"Lat pulldown\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 120\n        },\n        {\n          \"exercise\": \"Squats\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 180\n        },\n        {\n          \"exercise\": \"Plank\",\n          \"sets\": 3,\n          \"reps\": 30,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 100\n        }\n      ],\n      \"total_calories\": 550\n    },\n    \"Tuesday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Bicep curls\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 120\n        },\n        {\n          \"exercise\": \"Tricep dips\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 100\n        },\n        {\n          \"exercise\": \"Lunges\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 150\n        },\n        {\n          \"exercise\": \"Russian twists\",\n          \"sets\": 3,\n          \"reps\": 20,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 80\n        }\n      ],\n      \"total_calories\": 450\n    },\n    \"Wednesday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Shoulder press\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 130\n        },\n        {\n          \"exercise\": \"Seated rows\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 110\n        },\n        {\n          \"exercise\": \"Deadlifts\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 200\n        },\n        {\n          \"exercise\": \"Plank\",\n          \"sets\": 3,\n          \"reps\": 30,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 100\n        }\n      ],\n      \"total_calories\": 540\n    },\n    \"Thursday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Hammer curls\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 120\n        },\n        {\n          \"exercise\": \"Tricep pushdowns\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 100\n        },\n        {\n          \"exercise\": \"Step-ups\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 150\n        },\n        {\n          \"exercise\": \"Russian twists\",\n          \"sets\": 3,\n          \"reps\": 20,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 80\n        }\n      ],\n      \"total_calories\": 450\n    },\n    \"Friday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Bench press\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 150\n        },\n        {\n          \"exercise\": \"Lat pulldown\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 120\n        },\n        {\n          \"exercise\": \"Squats\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 180\n        },\n        {\n          \"exercise\": \"Plank\",\n          \"sets\": 3,\n          \"reps\": 30,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 100\n        }\n      ],\n      \"total_calories\": 550\n    },\n    \"Saturday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Bicep curls\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 120\n        },\n        {\n          \"exercise\": \"Tricep dips\",\n          \"sets\": 3,\n          \"reps\": 10,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 70,\n          \"calories\": 100\n        },\n        {\n          \"exercise\": \"Lunges\",\n          \"sets\": 3,\n          \"reps\": 12,\n          \"rest\": 60,\n          \"duration\": 30,\n          \"intensity\": 80,\n          \"calories\": 150\n        },\n        {\n          \"exercise\": \"Russian twists\",\n          \"sets\": 3,\n          \"reps\": 20,\n          \"rest\": 30,\n          \"duration\": 60,\n          \"intensity\": 60,\n          \"calories\": 80\n        }\n      ],\n      \"total_calories\": 450\n    },\n    \"Sunday\": {\n      \"exercises\": [\n        {\n          \"exercise\": \"Rest\",\n          \"sets\": 0,\n          \"reps\": 0,\n          \"rest\": 0,\n          \"duration\": 0,\n          \"intensity\": 0,\n          \"calories\": 0\n        }\n      ],\n      \"total_calories\": 0\n    }\n  }\n}",
    "mealSchedule": "{\n  \"schedule\": {\n    \"Monday\": {\n      \"breakfast\": \"Oatmeal with berries and almond butter\",\n      \"snack1\": \"Greek yogurt with mixed nuts\",\n      \"lunch\": \"Grilled chicken breast with quinoa and roasted vegetables\",\n      \"snack2\": \"Protein shake with banana\",\n      \"dinner\": \"Salmon with sweet potato and steamed broccoli\",\n      \"nutrition_totals\": {\n        \"calories\": 2000,\n        \"carbohydrates\": 200,\n        \"protein\": 180,\n        \"fat\": 60\n      }\n    },\n    \"Tuesday\": {\n      \"breakfast\": \"Egg white omelette with spinach and feta cheese\",\n      \"snack1\": \"Apple slices with peanut butter\",\n      \"lunch\": \"Turkey wrap with whole wheat tortilla, avocado, and lettuce\",\n      \"snack2\": \"Cottage cheese with pineapple chunks\",\n      \"dinner\": \"Lean beef stir-fry with brown rice and mixed vegetables\",\n      \"nutrition_totals\": {\n        \"calories\": 1900,\n        \"carbohydrates\": 180,\n        \"protein\": 170,\n        \"fat\": 55\n      }\n    },\n    \"Wednesday\": {\n      \"breakfast\": \"Whole grain toast with avocado and poached eggs\",\n      \"snack1\": \"Protein bar\",\n      \"lunch\": \"Grilled shrimp salad with mixed greens, tomatoes, and balsamic dressing\",\n      \"snack2\": \"Mixed berries with cottage cheese\",\n      \"dinner\": \"Chicken fajitas with whole  [...]

2023-07-17 05:46 UTC, kennyjhcheng commented
@d-x-s The response in your docs, and the example you gave, are not the same

2023-07-17 05:50 UTC, kennyjhcheng requested changes
just fix the docs/example so that they match so I know for sure which response format is correct.

Ping me ill approve right after

2023-07-18 06:25 UTC, kennyjhcheng approved these changes

2023-07-18 06:55 UTC, ckev07 approved these changes

2023-07-18 07:08 UTC, merged