Create chatbot
jakji93/airon-fitness pull request #63
Opened 2023-07-21 07:59 UTC by kevin-wu01

2023-07-24 02:47 UTC, kennyjhcheng commented
Make sure to merge latest main, missing some of the bugs that were fixed in previous PRs.

There's a bug for when you 
* don't have an existing schedule
* use chat-box to "view meal/workout plan" 
* "Yes" for adding a custom input
* Type a custom input

I was thinking maybe the chat bot just says "cannot create custom input, no schedule exists yet" and returns to the first prompt?

<img width="580" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/7b4cb01e-3c1f-459c-9dd2-bbdc3d3ef67e">

<img width="667" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/fd9e244e-88d7-4375-8887-384d636a2bf1">

2023-07-24 02:48 UTC, kennyjhcheng requested changes
Make sure to merge latest main, missing some of the bugs that were fixed in previous PRs.

There's a bug for when you 
* don't have an existing schedule
* use chat-box to "view meal/workout plan" 
* "Yes" for adding a custom input
* Type a custom input

I was thinking maybe the chat bot just says "cannot create custom input, no schedule exists yet" and returns to the first prompt?

<img width="580" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/7b4cb01e-3c1f-459c-9dd2-bbdc3d3ef67e">

<img width="667" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/fd9e244e-88d7-4375-8887-384d636a2bf1">

2023-07-26 08:35 UTC, kevin-wu01 commented
> Make sure to merge latest main, missing some of the bugs that were fixed in previous PRs.
> 
> There's a bug for when you
> 
> * don't have an existing schedule
> * use chat-box to "view meal/workout plan"
> * "Yes" for adding a custom input
> * Type a custom input
> 
> I was thinking maybe the chat bot just says "cannot create custom input, no schedule exists yet" and returns to the first prompt?
> 
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/67628346/255458284-7b4cb01e-3c1f-459c-9dd2-bbdc3d3ef67e.png"> <img alt="image" width="667" src="https://user-images.githubusercontent.com/67628346/255458243-fd9e244e-88d7-4375-8887-384d636a2bf1.png">

@kennyjhcheng I looked into this as I added logic for handling when no schedule exists when a user tries to add custom input. The `UseEffects` in the stats and tabbed schedule that reset the state of the slice was causing the `isError` state to be reset to false after it's set to true. Since I have logic that relies on this isError state to know if the schedule doesn't exist, it was causing it to break. Is there a reason why we need to reset the state whenever any of the following changes? `[workoutSchedule, mealSchedule, isError, isSuccess, message, dispatch]`

2023-07-27 16:51 UTC, jakji93 commented
Unless is already implemented, is it possible to add a command just to generate a fresh set of schedules? I don't think the user have a way to get a clean state (no custom input) schedule yet. I think it would be good ux to allow user revert to a default state

2023-07-29 06:12 UTC, kevin-wu01 commented
> Unless is already implemented, is it possible to add a command just to generate a fresh set of schedules? I don't think the user have a way to get a clean state (no custom input) schedule yet. I think it would be good ux to allow user revert to a default state

I currently don't have functionality to generate a new schedule if one already exists, I think in terms of priorities I'll come back to this after I'm done with the workout history.

2023-07-30 00:58 UTC, kennyjhcheng commented on client/src/components/Home/ChatArea/ChatArea.jsx
> +    await dispatch(getWorkoutAndMealSchedule());
maybe check so it's not unnecessarily calling `get`
```
if (!store.getState().workoutAndMealSchedule.workoutSchedule
      || !store.getState.workoutAndMealSchedule.workoutSchedule)
```

2023-07-30 00:58 UTC, kennyjhcheng commented on client/src/components/Home/ChatArea/ChatArea.jsx
> +          await dispatch(scheduleMode === 'Workout' ? getWorkoutSchedule() : getMealSchedule());
is it necessary to call `get` here? since we already have the schedules in store if they are already generated.

they are automatically loaded to store when you enter home page

2023-07-30 00:59 UTC, kennyjhcheng approved these changes

2023-07-30 08:06 UTC, jakji93 approved these changes

2023-07-31 17:54 UTC, jakji93 commented
There is a bit of delay when trying to select No after Viewing schedule, I'm assuming is the same issue Kenny brought up where the application is trying to retrieve from db instead of using store

2023-07-31 18:00 UTC, jakji93 commented on client/src/services/WorkoutAndMealScheduleService.js
> +  const apiUrl = `${process.env.REACT_APP_SERVER_API_BASE}/mock/workoutSchedule/`;
Should also switch from using mock to real api now

2023-08-01 06:08 UTC, kevin-wu01 commented on client/src/components/Home/ChatArea/ChatArea.jsx
> +    await dispatch(getWorkoutAndMealSchedule());
there seems to be a race condition problem where the useEffect is being called before the initial `getWorkoutAndMealSchedule` that is called when the page loads so it seems like dispatch will always be called. I added the check if somehow useEffect gets called late. 

If we have time I'll look into this performance improvement

2023-08-01 06:39 UTC, jakji93 commented
- Not sure if is just on my end, the responsiveness of the option selection are still having delays even for selecting which plan to view. 
- when updating a schedule, should prevent user entering nothing as an input
- For new account, after generating new schedule with the button on the left table, the dropdown option for chat bot still only shows edit profile and generate schedule until page is refreshed. Not sure if this will be an easy fix, if not can possibly ignore

2023-08-01 07:38 UTC, kevin-wu01 commented
> * Not sure if is just on my end, the responsiveness of the option selection are still having delays even for selecting which plan to view.
> * when updating a schedule, should prevent user entering nothing as an input
> * For new account, after generating new schedule with the button on the left table, the dropdown option for chat bot still only shows edit profile and generate schedule until page is refreshed. Not sure if this will be an easy fix, if not can possibly ignore

1. I haven't experienced this issue on my side actually, unless you're referring to the issue with buttons requiring multiple clicks to register?
2. fixed
3. i'll look into this tmrw as it's getting late, if there aren't other concerns though I'll fix this in a follow-up pr

2023-08-01 15:57 UTC, jakji93 commented
> 1. I haven't experienced this issue on my side actually, unless you're referring to the issue with buttons requiring multiple clicks to register?
yea, sometimes it needs multiple clicks to register

2023-08-01 18:14 UTC, kevin-wu01 commented
I think that problem is present in other areas of the app afaik and isn't unique to just the chatbot, might be a material ui thing? there isn't any explicit code that should be causing a delay on button click

i'll try to look into it but i might put the fix (if i find it) in a new pr since it's not just for the bot

2023-08-01 18:44 UTC, jakji93 submitted a review, later dismissed

2023-08-02 04:10 UTC, kennyjhcheng commented
I'll look into the problems relating to need multiple clicks

2023-08-02 04:10 UTC, kennyjhcheng submitted a review, later dismissed

2023-08-02 08:17 UTC, kennyjhcheng approved these changes

2023-08-02 14:57 UTC, merged