About page
jakji93/airon-fitness pull request #77
Opened 2023-07-30 01:38 UTC by jakji93

-About us
-meet the team
-disclaimer

initial styling done by Kevin

2023-07-30 01:49 UTC, ckev07 submitted a review, later dismissed

2023-07-30 23:43 UTC, kennyjhcheng requested changes
<img width="1136" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/49e769a6-35f7-4158-8967-415b73900ab5">

2023-07-30 23:45 UTC, kennyjhcheng commented
My changes: 

<img width="1126" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/71bbb6de-37a8-4d1b-8481-ccefde29b740">

<img width="406" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/c9f659e1-1319-48d0-a808-8e4dade4264a">

2023-07-31 04:21 UTC, ckev07 approved these changes

2023-07-31 06:14 UTC, kennyjhcheng approved these changes

2023-07-31 06:15 UTC, merged