Schedule History UI
jakji93/airon-fitness pull request #81
Opened 2023-08-01 06:33 UTC by kevin-wu01

Implementation for a user's schedule history, content can be found on the user profile page.
- Adds a new POST `/userprofile/history` route to get the paginated user's history
- Each page has 6 tiles. Tiles contain the date it was generated on and the type of schedule, clicking opens a dropdown that contains the schedule details

2023-08-01 07:02 UTC, ckev07 requested changes
No console errors, but seeing unexpected output in the FE where:
- Workout is displayed as undefined in the Workout Schedule Component
- Meal Plan displays an extra row of "undefined: undefined sets of undefined reps with undefined seconds of rest" in the Meal Schedule Component (possibly because you're trying to display the nutritional macros for each day when that is removed in the Meal Plan Component in the FE?)

Please take a look at the images below for your reference, thanks!
![image_720](https://github.com/jakji93/airon-fitness/assets/26811451/89095c41-f9fa-470d-ae54-db14c9cff0b7)
![image_720](https://github.com/jakji93/airon-fitness/assets/26811451/068f4f3a-ed3c-4c09-9a62-dfc58534a783)

2023-08-03 08:34 UTC, kevin-wu01 commented
> No console errors, but seeing unexpected output in the FE where:
> 
> * Workout is displayed as undefined in the Workout Schedule Component
> * Meal Plan displays an extra row of "undefined: undefined sets of undefined reps with undefined seconds of rest" in the Meal Schedule Component (possibly because you're trying to display the nutritional macros for each day when that is removed in the Meal Plan Component in the FE?)
> 
> Please take a look at the images below for your reference, thanks! ![image_720](https://user-images.githubusercontent.com/26811451/257431862-89095c41-f9fa-470d-ae54-db14c9cff0b7.png) ![image_720](https://user-images.githubusercontent.com/26811451/257431879-068f4f3a-ed3c-4c09-9a62-dfc58534a783.png)

Thanks for the callout should be fixed now, I think I was testing with bad data in the original implementation.

2023-08-04 23:56 UTC, kennyjhcheng commented
Fixed styling a bit: 

<img width="391" alt="image" src="https://github.com/jakji93/airon-fitness/assets/67628346/ee7e9d5d-7914-45ef-b988-de05c1dd4714">

2023-08-05 00:29 UTC, ckev07 approved these changes

2023-08-05 00:54 UTC, kennyjhcheng approved these changes

2023-08-05 00:56 UTC, merged